config/routes.rb
Rails.application.routes.draw do

  get 'img/edit'

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  
  root 'home#index'
  resources :posts

  get "posts/:id/new_tweet" => "posts#new_tweet"
  get "posts/:id/create_tweet" => "posts#create_tweet"
  get "users/:id" => "users#show"
  get 'share_users/new'

  post "imgs/:id/update" => "imgs#update"
  post "imgs/:id/destroy" => "imgs#destroy"
  resources :profiles

  get "auth/:provider/callback" => "share_users#new"
  

end
>>>>>>> dd430146ee39250760873f4afc9b2ed26f2e105c

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="footer-container">
    <p>copy:2017-miiim by Ta2 & Ni5</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="topTitle">
        <% if @current_user %>
            <%= link_to("miiim", post_path) %>
            <% else%>
            <%= link_to("miiim", "/") %>
            <% end %>
        </div>
    <ul class="header-menus">
        

          <!-- deviseで使われるヘルパーメソッドでuser_signed_in?はログインしているかどうか -->
        <% if user_signed_in? %>
        <li>      
            <strong><%= link_to current_user.name, "/users/#{current_user.id}" %></strong>
        </li>
        <li>
            <% if current_user %>
            <%= current_user.id %>
            <% end %>
        </li>
        <li>        
                <%= button_to 'ログアウト', destroy_user_session_path , method: :delete,:class => "logout" %>
        </li>
        <li>
            <%= link_to("ユーザー一覧", "/users/index") %>
        </li>
        <li>
            <%= link_to"新規投稿", new_post_path %>
        </li>
        <li>
            <%= link_to"投稿一覧", posts_path %>
        </li>
        <li>
            <%= link_to("検索", "/tweets/top") %>
        </li>

        <% else %>
        <li>
            <%= link_to 'ログイン', new_user_session_path %>
        </li>
        <li>
            <%= link_to 'サインアップ', new_user_registration_path %>
        </li>
         <% end %>
    </ul>
</header>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>miiim</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <!-- テキストエリアの入力をリアルタイムプレビューするためのjquery-->
    <script>
        $(function() {
            $('body').keyup(function() {
                $('#livepreview').html($('#liveeditor').val());
                 $('#livepreview-title').html($('#liveeditor-title').val());

            });
        });
        
        
        $(function() {
        $('#liveeditor').froalaEditor();
        });

    </script>

  </head>
  
  <body>
    <%= render 'layouts/header'%>
      <div class="container">

          
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          

          
     　<% if flash[:notice] %>
       <div class="flash">
         <%= flash[:notice] %>
       </div>
     <% end %>
      <div class="main">
     <%= yield %>
      </div>
    </div>
        <%= render "layouts/footer" %>
  </body>
</html>